
import ButtonStateProvider from "./ButtonStateContext";
import "./globals.css";
import StyledComponentsRegistry from "./registry";

export const metadata = {
  title: "Leadster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body suppressHydrationWarning={true}>
        <StyledComponentsRegistry>
          <ButtonStateProvider>{children}</ButtonStateProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
